sonar.projectKey=jminango20_calidad-software-practica
sonar.organization=jminango20
sonar.projectName=Calidad Software Practica
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/*.pyc
sonar.python.version=3
